/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Samth
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        nu9 = new javax.swing.JLabel();
        nu8 = new javax.swing.JLabel();
        nu7 = new javax.swing.JLabel();
        nu6 = new javax.swing.JLabel();
        nu5 = new javax.swing.JLabel();
        nu4 = new javax.swing.JLabel();
        nu3 = new javax.swing.JLabel();
        nu2 = new javax.swing.JLabel();
        nu1 = new javax.swing.JLabel();
        container10 = new javax.swing.JLabel();
        container11 = new javax.swing.JLabel();
        container12 = new javax.swing.JLabel();
        container13 = new javax.swing.JLabel();
        container14 = new javax.swing.JLabel();
        container15 = new javax.swing.JLabel();
        container16 = new javax.swing.JLabel();
        container17 = new javax.swing.JLabel();
        container18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        princ = new javax.swing.JLabel();
        numContainer = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        num3 = new javax.swing.JLabel();
        num4 = new javax.swing.JLabel();
        num5 = new javax.swing.JLabel();
        sos = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        qtd = new javax.swing.JLabel();
        numContainer1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        colB = new javax.swing.JLabel();
        colI = new javax.swing.JLabel();
        colN = new javax.swing.JLabel();
        colG = new javax.swing.JLabel();
        colO = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(130, 99, 99));
        jPanel3.setLayout(null);

        nu9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(nu9);
        nu9.setBounds(30, 300, 40, 40);

        nu8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(nu8);
        nu8.setBounds(110, 300, 40, 40);

        nu7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(nu7);
        nu7.setBounds(190, 300, 40, 40);

        nu6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(nu6);
        nu6.setBounds(30, 390, 30, 40);

        nu5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(nu5);
        nu5.setBounds(110, 390, 30, 30);

        nu4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(nu4);
        nu4.setBounds(190, 390, 40, 40);

        nu3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(nu3);
        nu3.setBounds(30, 490, 30, 30);

        nu2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(nu2);
        nu2.setBounds(110, 490, 40, 40);

        nu1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(nu1);
        nu1.setBounds(190, 490, 40, 40);

        container10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container10);
        container10.setBounds(10, 270, 75, 92);

        container11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container11);
        container11.setBounds(90, 270, 75, 92);

        container12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container12);
        container12.setBounds(170, 270, 75, 92);

        container13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container13);
        container13.setBounds(10, 360, 75, 92);

        container14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container14);
        container14.setBounds(90, 360, 75, 92);

        container15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container15);
        container15.setBounds(170, 360, 75, 92);

        container16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container16);
        container16.setBounds(10, 460, 75, 92);

        container17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container17);
        container17.setBounds(90, 460, 75, 92);

        container18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container18);
        container18.setBounds(170, 460, 75, 90);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(640, 0, 260, 570);

        jPanel4.setBackground(new java.awt.Color(30, 42, 74));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        princ.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jPanel4.add(princ);
        princ.setBounds(70, 80, 60, 70);

        numContainer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bola.png"))); // NOI18N
        jPanel4.add(numContainer);
        numContainer.setBounds(30, 40, 150, 160);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(50, 70, 220, 250);

        jPanel1.setBackground(new java.awt.Color(30, 42, 74));
        jPanel1.setLayout(null);

        num3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(num3);
        num3.setBounds(170, 50, 20, 0);

        num4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(num4);
        num4.setBounds(240, 50, 20, 0);

        num5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(num5);
        num5.setBounds(310, 44, 20, 30);

        sos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sos.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sos);
        sos.setBounds(40, 40, 420, 50);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(50, 400, 500, 120);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("Sortear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(340, 260, 230, 60);

        jButton5.setText("x");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(852, 0, 50, 40);

        jTabbedPane1.addTab("Sortear", jPanel2);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel19.setText("Qtd. Impressão");
        jPanel7.add(jLabel19);
        jLabel19.setBounds(20, 20, 260, 50);

        qtd.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        jPanel7.add(qtd);
        qtd.setBounds(120, 120, 80, 90);

        numContainer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bola.png"))); // NOI18N
        jPanel7.add(numContainer1);
        numContainer1.setBounds(80, 80, 150, 170);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(560, 50, 300, 280);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("Gerar e Imprimir Cartela");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);
        jButton3.setBounds(560, 390, 310, 70);

        jPanel8.setLayout(null);

        colB.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        colB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colB.setText("B");
        jPanel8.add(colB);
        colB.setBounds(0, 0, 87, 78);

        colI.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        colI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colI.setText("I");
        jPanel8.add(colI);
        colI.setBounds(90, 0, 87, 78);

        colN.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        colN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colN.setText("N");
        jPanel8.add(colN);
        colN.setBounds(180, 0, 87, 78);

        colG.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        colG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colG.setText("G");
        jPanel8.add(colG);
        colG.setBounds(270, 0, 87, 78);

        colO.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        colO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colO.setText("O");
        jPanel8.add(colO);
        colO.setBounds(360, 0, 87, 78);

        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel20);
        jLabel20.setBounds(0, 80, 90, 80);

        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel21);
        jLabel21.setBounds(90, 80, 90, 80);

        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel22);
        jLabel22.setBounds(180, 80, 90, 80);

        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel23);
        jLabel23.setBounds(270, 80, 90, 80);

        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel24);
        jLabel24.setBounds(360, 80, 90, 80);

        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel25);
        jLabel25.setBounds(0, 160, 90, 80);

        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel26);
        jLabel26.setBounds(90, 160, 90, 80);

        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel27);
        jLabel27.setBounds(180, 160, 90, 80);

        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel28);
        jLabel28.setBounds(270, 160, 90, 80);

        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel29);
        jLabel29.setBounds(360, 160, 90, 80);

        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel30);
        jLabel30.setBounds(0, 240, 90, 80);

        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel31);
        jLabel31.setBounds(90, 240, 90, 80);

        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel32);
        jLabel32.setBounds(180, 240, 90, 80);

        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel33);
        jLabel33.setBounds(270, 240, 90, 80);

        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel34);
        jLabel34.setBounds(360, 240, 90, 80);

        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel35);
        jLabel35.setBounds(0, 320, 90, 80);

        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel36);
        jLabel36.setBounds(90, 320, 90, 80);

        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel37);
        jLabel37.setBounds(180, 320, 90, 80);

        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel38);
        jLabel38.setBounds(270, 320, 90, 80);

        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel39);
        jLabel39.setBounds(360, 320, 90, 80);

        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel40);
        jLabel40.setBounds(0, 400, 90, 80);

        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel41);
        jLabel41.setBounds(90, 400, 90, 80);

        jLabel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel42);
        jLabel42.setBounds(180, 400, 90, 80);

        jLabel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel43);
        jLabel43.setBounds(270, 400, 90, 80);

        jLabel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel44);
        jLabel44.setBounds(360, 400, 90, 80);

        jPanel6.add(jPanel8);
        jPanel8.setBounds(30, 50, 450, 480);

        jButton4.setText("x");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);
        jButton4.setBounds(852, 0, 50, 40);

        jTabbedPane1.addTab("Gerar Cartelas", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Model.pdfCartela.table();
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Controller.Def_DAO.Mostra();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colB;
    private javax.swing.JLabel colG;
    private javax.swing.JLabel colI;
    private javax.swing.JLabel colN;
    private javax.swing.JLabel colO;
    private javax.swing.JLabel container10;
    private javax.swing.JLabel container11;
    private javax.swing.JLabel container12;
    private javax.swing.JLabel container13;
    private javax.swing.JLabel container14;
    private javax.swing.JLabel container15;
    private javax.swing.JLabel container16;
    private javax.swing.JLabel container17;
    private javax.swing.JLabel container18;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JLabel nu1;
    public static javax.swing.JLabel nu2;
    public static javax.swing.JLabel nu3;
    public static javax.swing.JLabel nu4;
    public static javax.swing.JLabel nu5;
    public static javax.swing.JLabel nu6;
    public static javax.swing.JLabel nu7;
    public static javax.swing.JLabel nu8;
    public static javax.swing.JLabel nu9;
    public static javax.swing.JLabel num3;
    public static javax.swing.JLabel num4;
    public static javax.swing.JLabel num5;
    private javax.swing.JLabel numContainer;
    private javax.swing.JLabel numContainer1;
    public static javax.swing.JLabel princ;
    private javax.swing.JLabel qtd;
    public static javax.swing.JLabel sos;
    // End of variables declaration//GEN-END:variables
}

