/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Samth
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        num8 = new javax.swing.JLabel();
        num9 = new javax.swing.JLabel();
        num10 = new javax.swing.JLabel();
        num11 = new javax.swing.JLabel();
        num12 = new javax.swing.JLabel();
        num13 = new javax.swing.JLabel();
        num14 = new javax.swing.JLabel();
        num15 = new javax.swing.JLabel();
        num16 = new javax.swing.JLabel();
        num17 = new javax.swing.JLabel();
        num18 = new javax.swing.JLabel();
        num19 = new javax.swing.JLabel();
        num20 = new javax.swing.JLabel();
        num21 = new javax.swing.JLabel();
        num22 = new javax.swing.JLabel();
        num23 = new javax.swing.JLabel();
        num24 = new javax.swing.JLabel();
        num25 = new javax.swing.JLabel();
        container1 = new javax.swing.JLabel();
        container2 = new javax.swing.JLabel();
        container3 = new javax.swing.JLabel();
        container4 = new javax.swing.JLabel();
        container5 = new javax.swing.JLabel();
        container6 = new javax.swing.JLabel();
        container7 = new javax.swing.JLabel();
        container8 = new javax.swing.JLabel();
        container9 = new javax.swing.JLabel();
        container10 = new javax.swing.JLabel();
        container11 = new javax.swing.JLabel();
        container12 = new javax.swing.JLabel();
        container13 = new javax.swing.JLabel();
        container14 = new javax.swing.JLabel();
        container15 = new javax.swing.JLabel();
        container16 = new javax.swing.JLabel();
        container17 = new javax.swing.JLabel();
        container18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        num = new javax.swing.JLabel();
        numContainer = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        num1 = new javax.swing.JLabel();
        num1Container = new javax.swing.JLabel();
        num2 = new javax.swing.JLabel();
        num2Container = new javax.swing.JLabel();
        num3 = new javax.swing.JLabel();
        num3Container = new javax.swing.JLabel();
        num4 = new javax.swing.JLabel();
        num4Container = new javax.swing.JLabel();
        num5 = new javax.swing.JLabel();
        num5Container = new javax.swing.JLabel();
        num6 = new javax.swing.JLabel();
        num6Container = new javax.swing.JLabel();
        num7 = new javax.swing.JLabel();
        num7Container = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        qtd = new javax.swing.JLabel();
        numContainer1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        colB = new javax.swing.JLabel();
        colI = new javax.swing.JLabel();
        colN = new javax.swing.JLabel();
        colG = new javax.swing.JLabel();
        colO = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(130, 99, 99));
        jPanel3.setLayout(null);

        num8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num8);
        num8.setBounds(30, 30, 34, 30);

        num9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num9);
        num9.setBounds(110, 30, 30, 30);

        num10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num10);
        num10.setBounds(190, 30, 30, 30);

        num11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num11);
        num11.setBounds(30, 120, 30, 30);

        num12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num12);
        num12.setBounds(110, 120, 30, 30);

        num13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num13);
        num13.setBounds(190, 120, 30, 30);

        num14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num14);
        num14.setBounds(30, 200, 40, 40);

        num15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num15);
        num15.setBounds(110, 210, 40, 40);

        num16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num16);
        num16.setBounds(190, 210, 40, 40);

        num17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num17);
        num17.setBounds(30, 300, 40, 40);

        num18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num18);
        num18.setBounds(110, 300, 40, 40);

        num19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num19);
        num19.setBounds(190, 300, 40, 40);

        num20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num20);
        num20.setBounds(30, 390, 30, 40);

        num21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num21);
        num21.setBounds(110, 390, 30, 30);

        num22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num22);
        num22.setBounds(190, 390, 40, 40);

        num23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num23);
        num23.setBounds(30, 490, 30, 30);

        num24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num24);
        num24.setBounds(110, 490, 40, 40);

        num25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(num25);
        num25.setBounds(190, 490, 40, 40);

        container1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container1);
        container1.setBounds(10, 0, 75, 92);

        container2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container2);
        container2.setBounds(90, 0, 75, 92);

        container3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container3);
        container3.setBounds(170, 0, 75, 92);

        container4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container4);
        container4.setBounds(10, 90, 75, 92);

        container5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container5);
        container5.setBounds(90, 90, 75, 92);

        container6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container6);
        container6.setBounds(170, 90, 75, 92);

        container7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container7);
        container7.setBounds(10, 180, 75, 92);

        container8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container8);
        container8.setBounds(90, 180, 75, 92);

        container9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container9);
        container9.setBounds(170, 180, 75, 92);

        container10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container10);
        container10.setBounds(10, 270, 75, 92);

        container11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container11);
        container11.setBounds(90, 270, 75, 92);

        container12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container12);
        container12.setBounds(170, 270, 75, 92);

        container13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container13);
        container13.setBounds(10, 360, 75, 92);

        container14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container14);
        container14.setBounds(90, 360, 75, 92);

        container15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container15);
        container15.setBounds(170, 360, 75, 92);

        container16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container16);
        container16.setBounds(10, 460, 75, 92);

        container17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container17);
        container17.setBounds(90, 460, 75, 92);

        container18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container18);
        container18.setBounds(170, 460, 75, 90);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(640, 0, 250, 570);

        jPanel4.setBackground(new java.awt.Color(30, 42, 74));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        num.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jPanel4.add(num);
        num.setBounds(70, 80, 60, 70);

        numContainer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bola.png"))); // NOI18N
        jPanel4.add(numContainer);
        numContainer.setBounds(30, 40, 150, 160);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(50, 70, 220, 250);

        jPanel1.setBackground(new java.awt.Color(30, 42, 74));
        jPanel1.setLayout(null);

        num1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(num1);
        num1.setBounds(40, 50, 20, 20);

        num1Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bolinha.png"))); // NOI18N
        jPanel1.add(num1Container);
        num1Container.setBounds(30, 30, 49, 60);

        num2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(num2);
        num2.setBounds(100, 40, 30, 40);

        num2Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bolinha.png"))); // NOI18N
        jPanel1.add(num2Container);
        num2Container.setBounds(90, 30, 49, 60);

        num3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(num3);
        num3.setBounds(170, 50, 20, 0);

        num3Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bolinha.png"))); // NOI18N
        jPanel1.add(num3Container);
        num3Container.setBounds(160, 30, 49, 60);

        num4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(num4);
        num4.setBounds(240, 50, 20, 0);

        num4Container.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num4Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bolinha.png"))); // NOI18N
        jPanel1.add(num4Container);
        num4Container.setBounds(230, 30, 49, 60);

        num5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(num5);
        num5.setBounds(310, 44, 20, 30);

        num5Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bolinha.png"))); // NOI18N
        jPanel1.add(num5Container);
        num5Container.setBounds(300, 30, 49, 60);

        num6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(num6);
        num6.setBounds(372, 50, 20, 20);

        num6Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bolinha.png"))); // NOI18N
        jPanel1.add(num6Container);
        num6Container.setBounds(360, 30, 49, 60);

        num7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(num7);
        num7.setBounds(430, 40, 30, 40);

        num7Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bolinha.png"))); // NOI18N
        jPanel1.add(num7Container);
        num7Container.setBounds(420, 30, 49, 60);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(50, 400, 500, 120);

        jPanel5.setBackground(java.awt.SystemColor.activeCaptionBorder);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("Sortear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(340, 260, 230, 60);

        jTabbedPane1.addTab("Sortear", jPanel2);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel19.setText("Qtd. Impressão");
        jPanel7.add(jLabel19);
        jLabel19.setBounds(20, 20, 260, 50);

        qtd.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        qtd.setText("75");
        jPanel7.add(qtd);
        qtd.setBounds(120, 120, 80, 90);

        numContainer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bola.png"))); // NOI18N
        jPanel7.add(numContainer1);
        numContainer1.setBounds(80, 80, 150, 170);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(560, 50, 300, 280);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Gerar Cartela");
        jPanel6.add(jButton2);
        jButton2.setBounds(560, 360, 290, 70);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("Imprimir Cartelas");
        jPanel6.add(jButton3);
        jButton3.setBounds(560, 460, 290, 70);

        jPanel8.setLayout(null);

        colB.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        colB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colB.setText("B");
        jPanel8.add(colB);
        colB.setBounds(0, 0, 87, 78);

        colI.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        colI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colI.setText("I");
        jPanel8.add(colI);
        colI.setBounds(90, 0, 87, 78);

        colN.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        colN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colN.setText("N");
        jPanel8.add(colN);
        colN.setBounds(180, 0, 87, 78);

        colG.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        colG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colG.setText("G");
        jPanel8.add(colG);
        colG.setBounds(270, 0, 87, 78);

        colO.setFont(new java.awt.Font("Tahoma", 0, 64)); // NOI18N
        colO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colO.setText("O");
        jPanel8.add(colO);
        colO.setBounds(360, 0, 87, 78);

        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel20);
        jLabel20.setBounds(0, 80, 90, 80);

        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel21);
        jLabel21.setBounds(90, 80, 90, 80);

        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel22);
        jLabel22.setBounds(180, 80, 90, 80);

        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel23);
        jLabel23.setBounds(270, 80, 90, 80);

        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel24);
        jLabel24.setBounds(360, 80, 90, 80);

        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel25);
        jLabel25.setBounds(0, 160, 90, 80);

        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel26);
        jLabel26.setBounds(90, 160, 90, 80);

        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel27);
        jLabel27.setBounds(180, 160, 90, 80);

        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel28);
        jLabel28.setBounds(270, 160, 90, 80);

        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel29);
        jLabel29.setBounds(360, 160, 90, 80);

        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel30);
        jLabel30.setBounds(0, 240, 90, 80);

        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel31);
        jLabel31.setBounds(90, 240, 90, 80);

        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel32);
        jLabel32.setBounds(180, 240, 90, 80);

        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel33);
        jLabel33.setBounds(270, 240, 90, 80);

        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel34);
        jLabel34.setBounds(360, 240, 90, 80);

        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel35);
        jLabel35.setBounds(0, 320, 90, 80);

        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel36);
        jLabel36.setBounds(90, 320, 90, 80);

        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel37);
        jLabel37.setBounds(180, 320, 90, 80);

        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel38);
        jLabel38.setBounds(270, 320, 90, 80);

        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel39);
        jLabel39.setBounds(360, 320, 90, 80);

        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel40);
        jLabel40.setBounds(0, 400, 90, 80);

        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel41);
        jLabel41.setBounds(90, 400, 90, 80);

        jLabel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel42);
        jLabel42.setBounds(180, 400, 90, 80);

        jLabel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel43);
        jLabel43.setBounds(270, 400, 90, 80);

        jLabel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel44);
        jLabel44.setBounds(360, 400, 90, 80);

        jPanel6.add(jPanel8);
        jPanel8.setBounds(30, 50, 450, 480);

        jTabbedPane1.addTab("Gerar Cartelas", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Controller.Def_DAO.Armazena(Controller.Def_DAO.Sorteia());
        Controller.Def_DAO.Mostra();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colB;
    private javax.swing.JLabel colG;
    private javax.swing.JLabel colI;
    private javax.swing.JLabel colN;
    private javax.swing.JLabel colO;
    private javax.swing.JLabel container1;
    private javax.swing.JLabel container10;
    private javax.swing.JLabel container11;
    private javax.swing.JLabel container12;
    private javax.swing.JLabel container13;
    private javax.swing.JLabel container14;
    private javax.swing.JLabel container15;
    private javax.swing.JLabel container16;
    private javax.swing.JLabel container17;
    private javax.swing.JLabel container18;
    private javax.swing.JLabel container2;
    private javax.swing.JLabel container3;
    private javax.swing.JLabel container4;
    private javax.swing.JLabel container5;
    private javax.swing.JLabel container6;
    private javax.swing.JLabel container7;
    private javax.swing.JLabel container8;
    private javax.swing.JLabel container9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JLabel num;
    public static javax.swing.JLabel num1;
    public static javax.swing.JLabel num10;
    public static javax.swing.JLabel num11;
    public static javax.swing.JLabel num12;
    public static javax.swing.JLabel num13;
    public static javax.swing.JLabel num14;
    public static javax.swing.JLabel num15;
    public static javax.swing.JLabel num16;
    public static javax.swing.JLabel num17;
    public static javax.swing.JLabel num18;
    public static javax.swing.JLabel num19;
    private javax.swing.JLabel num1Container;
    public static javax.swing.JLabel num2;
    public static javax.swing.JLabel num20;
    public static javax.swing.JLabel num21;
    public static javax.swing.JLabel num22;
    public static javax.swing.JLabel num23;
    public static javax.swing.JLabel num24;
    public static javax.swing.JLabel num25;
    private javax.swing.JLabel num2Container;
    public static javax.swing.JLabel num3;
    private javax.swing.JLabel num3Container;
    public static javax.swing.JLabel num4;
    private javax.swing.JLabel num4Container;
    public static javax.swing.JLabel num5;
    private javax.swing.JLabel num5Container;
    public static javax.swing.JLabel num6;
    private javax.swing.JLabel num6Container;
    public static javax.swing.JLabel num7;
    private javax.swing.JLabel num7Container;
    public static javax.swing.JLabel num8;
    public static javax.swing.JLabel num9;
    private javax.swing.JLabel numContainer;
    private javax.swing.JLabel numContainer1;
    private javax.swing.JLabel qtd;
    // End of variables declaration//GEN-END:variables
}

