/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Alunos
 */
public class Roleta_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Roleta_GUI
     */
    public Roleta_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        container9 = new javax.swing.JLabel();
        container10 = new javax.swing.JLabel();
        container11 = new javax.swing.JLabel();
        container12 = new javax.swing.JLabel();
        container13 = new javax.swing.JLabel();
        container14 = new javax.swing.JLabel();
        container15 = new javax.swing.JLabel();
        container16 = new javax.swing.JLabel();
        container17 = new javax.swing.JLabel();
        container18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        num = new javax.swing.JLabel();
        numContainer = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        num1 = new javax.swing.JLabel();
        num1Container = new javax.swing.JLabel();
        num2 = new javax.swing.JLabel();
        num2Container = new javax.swing.JLabel();
        num3 = new javax.swing.JLabel();
        num3Container = new javax.swing.JLabel();
        num4 = new javax.swing.JLabel();
        num4Container = new javax.swing.JLabel();
        num5 = new javax.swing.JLabel();
        num5Container = new javax.swing.JLabel();
        num6 = new javax.swing.JLabel();
        num6Container = new javax.swing.JLabel();
        num7 = new javax.swing.JLabel();
        num7Container = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(130, 99, 99));
        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("87");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(200, 260, 16, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("32");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(30, 360, 16, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("41");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(120, 360, 16, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("03");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(210, 360, 16, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("73");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(40, 450, 16, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("81");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(120, 450, 16, 17);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("30");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(200, 450, 16, 17);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("46");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(40, 550, 16, 17);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("18");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(120, 550, 16, 17);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("32");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(200, 550, 16, 17);

        container9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container9);
        container9.setBounds(176, 218, 75, 92);

        container10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container10);
        container10.setBounds(10, 316, 75, 92);

        container11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container11);
        container11.setBounds(95, 316, 75, 92);

        container12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container12);
        container12.setBounds(176, 316, 75, 92);

        container13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container13);
        container13.setBounds(10, 414, 75, 92);

        container14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container14);
        container14.setBounds(95, 414, 75, 92);

        container15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container15);
        container15.setBounds(176, 414, 75, 92);

        container16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container16);
        container16.setBounds(10, 512, 75, 92);

        container17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container17);
        container17.setBounds(95, 512, 75, 92);

        container18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BolaMedia.png"))); // NOI18N
        jPanel3.add(container18);
        container18.setBounds(176, 512, 75, 92);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(640, 0, 270, 610);

        jPanel4.setBackground(new java.awt.Color(30, 42, 74));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        num.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        num.setText("75");
        jPanel4.add(num);
        num.setBounds(70, 80, 60, 70);

        numContainer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bola.png"))); // NOI18N
        jPanel4.add(numContainer);
        numContainer.setBounds(30, 40, 150, 160);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(50, 70, 220, 250);

        jPanel1.setBackground(new java.awt.Color(30, 42, 74));
        jPanel1.setLayout(null);

        num1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num1.setText("15");
        jPanel1.add(num1);
        num1.setBounds(40, 50, 20, 20);

        num1Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bolinha.png"))); // NOI18N
        jPanel1.add(num1Container);
        num1Container.setBounds(30, 30, 49, 60);

        num2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num2.setText("70");
        num2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(num2);
        num2.setBounds(100, 40, 30, 40);

        num2Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bolinha.png"))); // NOI18N
        jPanel1.add(num2Container);
        num2Container.setBounds(90, 30, 49, 60);

        num3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num3.setText("60");
        jPanel1.add(num3);
        num3.setBounds(170, 50, 20, 17);

        num3Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bolinha.png"))); // NOI18N
        jPanel1.add(num3Container);
        num3Container.setBounds(160, 30, 49, 60);

        num4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num4.setText("43");
        jPanel1.add(num4);
        num4.setBounds(240, 50, 20, 17);

        num4Container.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num4Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bolinha.png"))); // NOI18N
        jPanel1.add(num4Container);
        num4Container.setBounds(230, 30, 49, 60);

        num5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num5.setText("24");
        jPanel1.add(num5);
        num5.setBounds(310, 44, 20, 30);

        num5Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bolinha.png"))); // NOI18N
        jPanel1.add(num5Container);
        num5Container.setBounds(300, 30, 49, 60);

        num6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num6.setText("02");
        jPanel1.add(num6);
        num6.setBounds(372, 50, 20, 20);

        num6Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bolinha.png"))); // NOI18N
        jPanel1.add(num6Container);
        num6Container.setBounds(360, 30, 49, 60);

        num7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num7.setText("54");
        num7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(num7);
        num7.setBounds(430, 40, 30, 40);

        num7Container.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bolinha.png"))); // NOI18N
        jPanel1.add(num7Container);
        num7Container.setBounds(420, 30, 49, 60);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(50, 400, 500, 120);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("Sortear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(340, 260, 230, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Roleta_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Roleta_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Roleta_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Roleta_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Roleta_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel container10;
    private javax.swing.JLabel container11;
    private javax.swing.JLabel container12;
    private javax.swing.JLabel container13;
    private javax.swing.JLabel container14;
    private javax.swing.JLabel container15;
    private javax.swing.JLabel container16;
    private javax.swing.JLabel container17;
    private javax.swing.JLabel container18;
    private javax.swing.JLabel container9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel num;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel num1Container;
    private javax.swing.JLabel num2;
    private javax.swing.JLabel num2Container;
    private javax.swing.JLabel num3;
    private javax.swing.JLabel num3Container;
    private javax.swing.JLabel num4;
    private javax.swing.JLabel num4Container;
    private javax.swing.JLabel num5;
    private javax.swing.JLabel num5Container;
    private javax.swing.JLabel num6;
    private javax.swing.JLabel num6Container;
    private javax.swing.JLabel num7;
    private javax.swing.JLabel num7Container;
    private javax.swing.JLabel numContainer;
    // End of variables declaration//GEN-END:variables
}
